import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import { Toaster } from 'react-hot-toast';
import NextThemeProvider from '@/components/theme/NextThemeProvider';

export const metadata: Metadata = {
  title: 'codegenPro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#ffffff] dark:bg-[#2C2C2C] text-[#444444] dark:text-white'>
        <NextThemeProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </NextThemeProvider>
      </body>
    </html>
  )
}
